import Head from "next/head";
import Link from "next/link";

const Layout: React.FC = ({ children }) => {
    return (
        <div className="bg-gradient-to-b from-purple-400 to-cyan-800">
            <div className="mx-auto flex flex-col h-screen">
                <Head>
                    <title>Transportation | Health</title>
                    <meta
                        name="A tool to investigate the relationship between transportation infrastructure and human health"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className="self-center">
                    <Link href="/">
                        <a>
                            <h1 className="text-5xl font-bold text-slate-100 tracking-wider mt-14 transition hover:scale-105">
                                Transportation | Health
                            </h1>
                        </a>
                    </Link>
                </div>
                {children}
            </div>
        </div>
    );
};

export default Layout;
